export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const SWITCH_BREADCRUMB_SECTION = 'SWITCH_BREADCRUMB_SECTION'

export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const FETCH_JOBS_BEGIN = 'FETCH_JOBS_BEGIN'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR'

export const PAGINATION_JOBS_BEGIN = 'PAGINATION_JOBS_BEGIN'
export const PAGINATION_JOBS_SUCCESS = 'PAGINATION_JOBS_SUCCESS'
export const PAGINATION_JOBS_ERROR = 'PAGINATION_JOBS_ERROR'
