export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const FETCH_JOBS_BEGIN = 'FETCH_JOBS_BEGIN'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_ERROR = 'FETCH_JOBS_ERROR'
